### ISSUE TITLE
0.6 API update

### ISSUE THREAD

**Issue by phdsg** [The-XOR/RackPlugins#11]
my guess is you're doing it yourself.
might wanna drop a line here https://github.com/VCVRack/community/issues/269, before someone else does unnecessary work.

**Comment by The-XOR** [comment]
done, will be available in the next release

**Comment by phdsg** [comment]
is the source already in a branch to test?

**Comment by The-XOR** [comment]
osc branch.

Il giorno sab 24 feb 2018 alle 17:05 phdsg vn chfhn <
notifications@github.com> ha scritto:
