### ISSUE TITLE
Could you email old .6 version of rematch? Current rental version to big for my patches.

### ISSUE THREAD

**Issue by ryancolao** [The-XOR/RackPlugins#17]
I got in touch w Andrew before I updated he said all plug ins were compatible in .6.2b I had a lot of patches saved in .6. Everything went well w updating plug ins but when I updated renato had completely changed & the first version was completely gone from your github.. can you please email me the first .6 version of renato it work better with my patches, it’s not so big, it was small and powerful.l efficient. pls email me renato .6 the first version.  Couldn’t you have both versions of renato so those who want a simple sequencer over a big heavy processing sequencer  can choose?  Pls help I love renato 1, renato 2 is too big and heavy for my patches/computer I’m on a 2011 Mac Pro.. thanks

**Comment by ryancolao** [comment]
My email is ryancolaomedia@gmail.com hope you can help thank you

**Comment by The-XOR** [comment]
Sorry to hear that, but I haven't any old version of any plugin. Even if I
had, No way for me to compile a mac version as I am on PC.
Sorry,
X:

Il giorno ven 27 lug 2018 alle 02:45 ryancolao <notifications@github.com>
ha scritto:
