### ISSUE TITLE
Suggestion: save & switch presets?

### ISSUE THREAD

**Issue by Chaircrusher** [The-XOR/RackPlugins#18]
Right now if I want to save a particular sequence I can save it as a preset file.
What would rule would be  a mechanism to e.g. have a directory of one or more presets, and switch between presets under voltage control?

Similar to how Radio Music handles directories full of samples.

**Comment by The-XOR** [comment]
thank you for the suggestion. Something like this requires quite a lot of time and  work, so I am not sure if I will ever able to implement this.
Cheers.
