### ISSUE TITLE
Are you gonna make a build for vcv 1.0?

### ISSUE THREAD

**Issue by 77377** [The-XOR/RackPlugins#19]
Hi, I recently discovered your wonderful modules, man those sequencers ...love 'em the smaler things like Burst and Uncertain too. 

Are you gonna be on board with vcv v1.x? I really hope you do. (:

**Comment by smok-e** [comment]
I miss your modules in vcv v1.0

**Comment by The-XOR** [comment]
there is an experimental branch "uno" with all modules working

**Comment by Petervos2018** [comment]
Cool !
while you're at it could you take a look at renato (the lights on rows 1 to 3 are not working) (v0.6.2)

![renato-bug](https://user-images.githubusercontent.com/46076474/61811732-652c7e00-ae42-11e9-9f89-a0524121f2fe.png)

Love the Klee (liked the white skin better ;) ) spiralone, z8k etc...

Greetings Peter.

**Comment by smok-e** [comment]
@the-XOR, thanks for your repley, this is really good news.

are there any compiled versions of the uno branch for windows?

**Comment by The-XOR** [comment]
Soon. I am updating the clock generator in order to drive it with midi
start and stop

Il giorno mer 24 lug 2019 alle 20:06 Stephan <notifications@github.com> ha
scritto:

**Comment by The-XOR** [comment]
a compiled version for windows is now available in Assets

**Comment by Petervos2018** [comment]
Thanks for fixing the Renato lights 

Greetings Peter

**Comment by The-XOR** [comment]
😁

Il gio 25 lug 2019, 14:58 Peter Vos <notifications@github.com> ha scritto:

**Comment by 77377** [comment]
I love u! 

Thanks for maintaining your suite of modules! 

Cheers!
