### ISSUE TITLE
Mac version?

### ISSUE THREAD

**Issue by psychonaut25** [The-XOR/RackPlugins#2]
Are there any plans in the works to port this to OSX?  Literally asking for a friend, haha... I have a friend I'd like to collab with who uses Mac.  I was considering looking into building and compiling from source for Mac, but since I use Windows I figure that'd be challenging unless I did it on my buddy's computer.

**Comment by sixstringeek** [comment]
Second...I am tempted to learn now, how to compile and do this stuff but Im a hardware nerd and can't code my way into a paper bag much less get out of one, but I want the Klee sequencer!!! This looks spectacular..

**Comment by The-XOR** [comment]
Hi,
I do not have a Mac, so it is impossible for me to compile a version for OS. The binary (compiled) version for WINDOWS ONLY can be found here
https://github.com/The-XOR/VCV-Sequencers/files/1600847/TheXOR-0.5.2-win.zip

cheers,
X:

**Comment by nay-seven** [comment]
Hello, someone had compiled  the 0.5.1 on Facebook, so i've add it in the French group, here it is
[TheXOR-0.5.1-mac.zip](https://github.com/The-XOR/RackPlugins/files/1660213/TheXOR-0.5.1-mac.zip)

**Comment by psychonaut25** [comment]
Thanks so much, nay-seven!  My friend says it's working for him.  I really appreciate the help~ cheers
