### ISSUE TITLE
Input reset on Spiralone V1

### ISSUE THREAD

**Issue by AlbZamoraBell** [The-XOR/RackPlugins#20]
When receiving a signal on any input reset, Spiralone changes stride, length and transpose parameters on all channels at random. I'm on Mac, I don't know if it happens on other OS.

I know this is still a work in progress to v1, so just a thing to keep up in mind. Thank you for the great work! :)

**Comment by AlbZamoraBell** [comment]
Oh my God! Nevermind, I just realized that I accidenatly connected my reset cable to the input in the middle. Silly me hahaha

**Comment by The-XOR** [comment]
Yes, that is the '/secret random randomizer'.it randomizes one of  stride,
transpose, mode, pitch.... Randomly

Il giorno sab 27 lug 2019 alle 00:13 AlbZamoraBell <notifications@github.com>
ha scritto:
