### ISSUE TITLE
Xswitch is transparent

### ISSUE THREAD

**Issue by spectromas** [The-XOR/RackPlugins#27]
Xswitch isn't rendering properly for me, it is transparent in the module browser and when it is loaded: 

![Screenshot_20190818_083321](https://user-images.githubusercontent.com/6443372/63221711-dedf2f80-c194-11e9-87e8-ced7a5572652.png)

I've had a look at the svg and I can't see anything weird or wrong.

**Comment by The-XOR** [comment]
will check, thanks.

**Comment by The-XOR** [comment]
1.1.1 is out, and I was not able to replicate this issue anyway
