### ISSUE TITLE
Knob Stored Value Bug

### ISSUE THREAD

**Issue by midiguru** [The-XOR/RackPlugins#32]
I'm using TheXOR 1.1.1 in VCV 1.1.4 (in Windows 7). What I've found is that in some conditions -- and I don't know the exact conditions, because I haven't yet found a way to duplicate it -- the stored knob values in z8k and Spiral are displayed on the panel but not used internally. This happens when a VCV patch has been stored and is later reloaded, and it doesn't seem to happen with simple patches, but has happened in two of the more complex patches that I saved a few days ago.

The attached video displays the problem as it appears in z8k. The knobs point various places, but when I click on them to edit the values, if you look closely you'll see that the knob _jumps_ to the highest value. That's what's being stored internally, and it's what you hear in the audio. When I readjust the knob back to something like its previously displayed value, the pitches being output to my oscillators change accordingly. When I do this to six or eight knobs, you'll start to hear the pattern of notes that I had originally stored when I saved the patch -- a pattern that was not reloaded properly.

[the_xor_knob_bug.zip](https://github.com/The-XOR/RackPlugins/files/3538601/the_xor_knob_bug.zip)

Great modules! I'm enjoying them.

--Jim Aikin (midiguru23@gmail.com)

**Comment by The-XOR** [comment]
Hi,
When you say some days ago... Did you save the patch from v1.1.0?
I am asking because values in 1.1.1 are much different, so there is no
retro compatibility.
Cheers,
X:


Il giorno dom 25 ago 2019 alle 22:33 midiguru <notifications@github.com> ha
scritto:

**Comment by midiguru** [comment]
It wasn't 1.1.0, but it may have been 1.1.2. In any case, now that I have re-edited the patch and stored it again, it loads properly. So I think you have the correct explanation.

**Comment by The-XOR** [comment]
Nice. I can put away my crystal ball. :-)

Il giorno dom 25 ago 2019 alle 23:28 midiguru <notifications@github.com> ha
scritto:
