### ISSUE TITLE
Holy sh*T nag nag nag is the best trigger sequencer in rack hands down!

### ISSUE THREAD

**Issue by 77377** [The-XOR/RackPlugins#38]
Hi don't know how else to reach you so I leave a ticket here:

I've been enjoying your quirky sequencers for a long while, and love them dearly. 

nag nag nag though is a  next level  gem and I'm deeply grateful you made it and maintain it.  

Keep up the good work! 
Cheers!

**Comment by The-XOR** [comment]
Hey, thanks a lot for the good words 
:-)
Have a lot of fun!!!!!!
