### ISSUE TITLE
Release latest version?

### ISSUE THREAD

**Issue by spectromas** [The-XOR/RackPlugins#41]
I just came here to see if there was any request for Rack v2 and noticed a few modules I hadn't seen before. Built from source and wow, there are fantastic updates. Are these not ready for release?

**Comment by The-XOR** [comment]
They are, but I do no have time to release them "officialy".
V2 release are not in the radar for now and for the foreseeable future.

**Comment by spectromas** [comment]
That's a real shame but understandable. Would you mind if someone adopts them for porting to V2 only?

**Comment by The-XOR** [comment]
As long as they remain open source, no problem.
