### ISSUE TITLE
M581 logo placement

### ISSUE THREAD

**Issue by MarcBoule** [The-XOR/RackPlugins#8]
Hi, I really like 581 sequencer, and I was wondering if there is a small issue with the placement of the XOR logo, since it seems to overwrite the "0 V" marking, as shown here in the left side:

![image](https://user-images.githubusercontent.com/33604154/36237031-7d807f1a-11c7-11e8-81c4-5d169b6e86e3.png)

Using v.0.5.1 of Rack, with v.0.5.5 of the M581, under windows 10.
Cheers!

**Comment by The-XOR** [comment]
You are right, and I know how ugly my interfaces are :-)
It will be fixed in the next release.
